### ISSUE TITLE
Kinda an issue? Player Toxicity

### ISSUE THREAD

**Issue by HRJDragon** [GemPowered/Issue-Tracker#12]
On my many years on GP loads of people have been supportive, kind and honest, and have always made GP different. It used to be that all of the hate was only a roleplay use in wars. Recently, a lot of homeworld players have been ganging up and taking down rebels that don't want to fight, they only want to do what they came to do. A lot of Homeworld players are also toxic to rebels, my friend tahi being told that "his mom was easy" by Jet. I'm not sure if this is player disrespect or not but it seems toxic to me. I don't know if this is a problem because most staff are homeworld and let it slip past them. Another issue i have is the unbalancement of the sides, meaning homeworld having many staff, the majority of players, and diamonds whereas the "rebels" have neutral players and limited staff. I really don't want to play GP if people like Jet continue to make this an unpleasant server. All I'm asking is that the old neutral class be re-added to players that don't want hate from homeworld, they just want to play gem powred.
-from labby
(this will probably get denied tbh why did i even try)

**Comment by HRJDragon** [comment]
wups *powered* spellin error

**Comment by Lusameme** [comment]
Though most of this is not a request nor a bug you should send this to someone like Tini or Riley about the toxicity and also put the neutral as a feature request separately

**Comment by HRJDragon** [comment]
sorry wasnt sure how to contact them
