### ISSUE TITLE
[Towny] No Outposts?

### ISSUE THREAD

**Issue by x-squidmaster-x** [GemPowered/Issue-Tracker#14]
So I go and try to make a outpost, and It wont let me. I just a message saying "[Towny] Not Registered"
Has outposts been disabled or is this a bug?

**Comment by Lusameme** [comment]
this just means your doing the wrong command all the commnands are listed here: http://towny.palmergames.com/towny/towny-commands/

**Comment by Lusameme** [comment]
tell me if it works

**Comment by x-squidmaster-x** [comment]
Im entering the right command.

**Comment by x-squidmaster-x** [comment]
Ah nevermind I was doing it wrong ;p
