### ISSUE TITLE
Out of Bounds

### ISSUE THREAD

**Issue by colbydray** [GemPowered/Issue-Tracker#15]
i was in the battlefield and i jump and jumped 
![2017-08-26_16 01 37](https://user-images.githubusercontent.com/3680439/29744676-d4afe76c-8a77-11e7-9268-788e87149227.png)
until i managed to get to the top
![2017-08-26_16 05 01](https://user-images.githubusercontent.com/3680439/29744694-57cbebfa-8a78-11e7-9cd2-ee8996e77a94.png)
and i jumped down

**Comment by TiniVi** [comment]
This build was not meant to be available yet, that was a mistake on our end.
