### ISSUE TITLE
BossAJ keeps killing me (not sure about other people)

### ISSUE THREAD

**Issue by SeaweedBrain** [GemPowered/Issue-Tracker#19]
The player Jet (Minecraft username - BossAJ) keeps killing me whenever he sees me. First he stated the needed my gem for something secret, then he revealed that he just wanted to level up. I am aware HW gems can level up when poofing and shattering people, but honestly I dont know if it's a valid excuse to kill me. He may have killed other players.
![2017-09-01_22 45 09](https://user-images.githubusercontent.com/31551015/29985683-b0ba72e6-8f68-11e7-99df-9593bac8170f.png)

**Comment by TiniVi** [comment]
This is not a server issue or feature request, please report this to a staff member next time.
