### ISSUE TITLE
Can't open anything or claim anything

### ISSUE THREAD

**Issue by BlueBirdAzurite** [GemPowered/Issue-Tracker#4]
I can't open chests, doors, furnaces, or anything like that. i also can't use towny to claim anything.

**Comment by TiniVi** [comment]
Can you specify where this is happening?

**Comment by BlueBirdAzurite** [comment]
im in the wild and whenever i try to open a chest or door or anything, it says "Not Allowed to Switch in the Wild."

**Comment by BlueBirdAzurite** [comment]
![image](https://user-images.githubusercontent.com/31323726/29685902-ee51f212-88e4-11e7-8c84-7deb3d7c8188.png)
like that
