### ISSUE TITLE
Beach City Shop's Wont work + Leveling up issue.

### ISSUE THREAD

**Issue by x-squidmaster-x** [GemPowered/Issue-Tracker#5]
Plain and simple the shops in beach city wont work. Can't sell and can't buy.

Also I have leveled up to 12 and I got a message in chat saying that I could choose a unique ability but where in the world do I do that? Is it a bug or what?

**Comment by TiniVi** [comment]
The prior is a bug, but the ladder is not. I just haven't finished the location to do that yet. It should be available by tomorrow.
