### ISSUE TITLE
Spawnkilling

### ISSUE THREAD

**Issue by HRJDragon** [GemPowered/Issue-Tracker#9]
Recently gangs of HW members have been targeting anyone to go to beach city, since no one said not to. Can beach city be a non pvp area since I can't get anywhere since spawnkillers give u combat tags? (btw frallerina and BossAJ were the main culprits i can send screenshots if neccessary) - love lab

**Comment by Lusameme** [comment]
this is not a bug nor a feature request please message staff on discord or the server for help with these kinds of issues
